---
- name: add repo file for elasticsearch
  copy: src=es.repo dest=/etc/yum.repos.d/es.repo

- name: debug1
  debug: var={{ master }}

- name: configure elasticsearch
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml

- name: install elasticsearch
  yum: name=elasticsearch state=latest
  notify:
  - restart elasticsearch

- name: enable elasticsearch on boot
  service: name=elasticsearch enabled=yes
