---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: drop rsyslog file in place
    copy: dest=/etc/rsyslog.conf src=files/rsyslog.conf

  - name: install packages
    yum: name={{ item }} state=latest
    with_items:
    - yum-cron
    - ansible

  - name: remove yum-cron-security
    yum: name=yum-cron-security state=absent

  - name: remove yum-cron-security file
    file: state=absent dest=/etc/yum/yum-cron-security.conf

  - name: configure yum-cron
    copy: dest=/etc/yum/yum-cron.conf src=files/yum-cron.conf 
  
  - name: configure ansible pull
    copy: dest=/etc/cron.d/ansible-pull src=files/ansible-pull

  - name: update root's authorized keys for ansible
    copy: dest=/root/.ssh/authorized_keys src=files/root-authorized_keys group=root mode=0600 owner=root 

  - name: update sshd configuration
    copy: dest=/etc/ssh/sshd_config src=files/sshd_config
    notify:
    - restart sshd

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
